version: '3.8'

services:
  trade.api:
    image: ${DOCKER_REGISTRY-}tradeapi
    container_name: trade.api
    build:
      context: .
      dockerfile: Trade.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - trade.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - postgres

  trade.database:
    image: postgres:13
    container_name: trade.database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tradedb"
    ports:
      - "5432:5432"
    volumes:
      - trade_db:/var/lib/postgresql/data
    networks:
      - postgres

  # trade.pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: trade.pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - trade.database
  #   networks:
  #     - postgres

volumes:
  trade_db:

networks:
    postgres:
        driver: bridge
